### ISSUE TITLE
fisher: Plugin not supported: "joseluisq/gitnow"

### ISSUE THREAD

**Issue by stefanfrede** [joseluisq/gitnow#34]
Hi!

I get the following message when installing `gitnow` with `fisher`:

```
❯ fisher install joseluisq/gitnow
fisher install version 4.2.0
Fetching https://codeload.github.com/joseluisq/gitnow/tar.gz/HEAD
fisher: Plugin not supported: "joseluisq/gitnow"
Support for .fish files outside a functions directory is deprecated https://github.com/jorgebucaran/fisher/issues/651
```

How do I avoid that?

Thanks!

**Comment by joseluisq** [comment]
Yeah I have just realized time ago too.
BTW You can also get more context about the "issue" on the description of this PR https://github.com/joseluisq/gitnow/pull/30#issue-584827802

Well basically I did introduce a [testing script](https://github.com/joseluisq/gitnow/blame/master/testing.fish) for Gitnow on the root of this repo weeks ago but without being aware about that "Fisher constraints" in its newest version (already mentioned).

Being said that, this constraint lets me in a crossroad since I don't want to pack my testing scripts to users.
So I can possibly just rename the file to `.sh` to "bypass" the constraint but It seems non-sense.

For now take a look at the [install section](https://github.com/joseluisq/gitnow#install) in the repo there are few alternatives to install this plugins until we find a proper workaround for Fisher.

**Comment by joseluisq** [comment]
I have managed the installation issue with Fisher so feel free to pull the latest changes.
